### ISSUE TITLE
Taranis QX7 XJT transceiver support

### ISSUE THREAD

**Issue by aquaforum** [ExpressLRS/ExpressLRS#1257]
I really liked this firmware on R9M. Is it possible to make a firmware for the built-in Taranis QX 7 radio? R9M has large antennas and 2.4 GHz receivers are very compact. 
Thanks.

**Comment by brandonrc** [comment]
@aquaforum the issue is the internal 2.4ghz hardware is not the sx1280 LoRa chip we need to use. So there is no way we could do that. 

One option would be to make an internal module that you could replace the frsky module with. 

I think your best option is to get a happy model 2.4ghz TX and use the whip antenna. Then you could hid that inside the TX case itself. Perfect for keeping everything nice and small :)
