### ISSUE TITLE
The lua page shows the fw version number is not a number

### ISSUE THREAD

**Issue by 594ak** [ExpressLRS/ExpressLRS#1499]
It should be because the firmware is compiled offline
Which .h file do I need to find?
Modify locally compiled firmware to display version number in LUA.

**Comment by commanderguy3001** [comment]
I don't quite understand the description of your issue, could you maybe explain that a little further:
- how the lua looks for you
- what you did to have it look like that
- why you think that it is wrong what's shown currently, and what you'd like to change

**Comment by pkendall64** [comment]
> It should be because the firmware is compiled offline Which .h file do I need to find? Modify locally compiled firmware to display version number in LUA.

If you are compiling locally and it's not a git checkout then the commands used to find the version number cannot work and you will end up with "unknown". If it's a local git checkout then it should be using the "tag" if a tag it checked out otherwise the branch name, which could be "HEAD" if you are on a disconnected head state.

So, this should be working as intended, depending on what you see as the version number.
