### ISSUE TITLE
Changing SSID/PW in the configurator seems to have no effect

### ISSUE THREAD

**Issue by dgrat** [ExpressLRS/ExpressLRS#1537]
## Current Behavior

Current hardware: DIY Tx and different Rx can be initially flashed by BF passthrough. 
I was successfully able to define an initial SSID and password. The Hardware was able to connect to my AP.
Yesterday, I updated the the firmwares of my 6 models and Tx successfully from 2.3 -> 2.4. 

Changing the SSID and password had no effect. 
They still connect to the old network. 
The network settings and the diversity settings in the configurator reset after you press the "back" button (after flashing). 

## Steps to Reproduce

Change the SSID and password in the ExpressLRS configurator and reflash.

## Possible Solution (Not obligatory)

I think it might be a bug somewhere.
It would be btw. awesome to change the SSID/PW via the Tx in the Lua Script.  

## Details

I use a DIY Tx and Matek receivers as well as the HappyModel receivers. They all behave similar.  I build with Win10. I can try Linux too if desired.

**Comment by pkendall64** [comment]
This is a bug which we have fixed in the master branch.
If you have configured a wifi in the configurator and one in the wifi page of the RX/TX then the wifi page overrides the flashed one. You can clear the configured one by going to the web page and "Forget" the configured ssid and it should then revert to using the flashed SSID and password.
