### ISSUE TITLE
Can't exit failsafe on 3.0.0-RC2

### ISSUE THREAD

**Issue by SolkGit** [ExpressLRS/ExpressLRS#1818]
## Current Behavior

Can't exit failsafe after control link is regained on 3.0.0-RC2.

## Steps to Reproduce

1. Radio control on
2. Quad on
3. Arm motors -> motors spin
4. Radio control off -> 'fail safe' blinking in osd, motors off
5. Radio control on -> control link regained, 'fail safe' still blinking in osd
6. Arm motors -> motors off, 'failsafe' is shown (not blinking, without space)

## Possible Solution (Not obligatory)

Set telemetry ratio to 'off' or use earlier versions e.g. 2.5.0 untill the problem is solved.
Update (09.09.2022 23:04): After setting Band to "Off" in VTX Administrator control CAN be regained powering on the radio controller with armed and disarmed motors. Tested with ELRS 2.5.0
Update (09.09.2022 23:22): 
- ELRS 3.0.0 and active VTX Administrator: control CAN'T be regained with arm switch on and off during power on of radio controller. Compared to 3.0.0 control can be regained with 2.5.0 at least if the arm switch is on.
- ELRS 3.0.0 and inactive VTX Administrator: control CAN be regained in every situation.

DON'T use GPS rescue with 3.0.0-RC2!!!

## Details

Release 2.5.0 works fine, but 3.0.0-RC2 fails to exit failsafe mode. As regulatory domain I use EU_CE_2400. 
Update (05.09.2022 20:20): also happens with ISM_2400. Can exit failsafe, if telemetry ratio is set to 'off' using 3.0.0-RC2.
Update (06.09.2022 21:01): Can exit failsafe without telemetry with CE and ISM.
Update (09.09.2022 00:06): https://youtu.be/psYtto7W_zM (3.0.0-RC2 CE_LBT Telemetry: Std)
Update (09.09.2022 00:08): https://youtu.be/1SdHO00Cg7E (3.0.0-RC2 CE_LBT Telemetry: Off)
Update (09.09.2022 00:10): https://youtu.be/ylKrlcbhQxw (2.5.0 CE)
- with 2.5.0 it depends on arm switch during power on of the radio controller whether I can exit failsafe mode or not
- motors armed during power on -> failsafe mode exit is possible
- motors disarmed during power on -> failsafe mode exit is not possible

Update (09.09.2022 19:26): https://youtu.be/IqGmx8LqS0Y
- tested ELRS 2.5.0 CE with BF 4.3.1, same results as with BF 4.3.0
- noticed "BST" warning (blinking once or twice), if the radio is powered on with disarmed motors or motors are disarmed before "BADRX" is visible in OSD

Update (09.09.2022 21:03): https://youtu.be/5MGbYP3bD4A
- tested ELRS 2.5.0 CE with iNav 5.1
- radio controller powered on with armed motors -> control regained
- radio controller powered on with disarmed motors -> control not regained

## Your Environment

- TX hardware: BETAFPV 2400 TX Micro 1000mW
- RX hardware: HGLRC HERMES 2400 RX or BETAFPV Nano 2400 RX
- Handset model: Eachine TX16S
- OpenTX version (including nightly number): EdgeTX 2.6.0
- ExpressLRS version (TX & RX MUST MATCH): 2.5.0 and 3.0.0-RC2
- Packet Rate: 500 Hz
- Telemetry Ratio: 1:128
- Update (06.09.2022 20:55): used flight control firmware
   - betaflight 4.2.0 with BETAFPV Nano 2400 RX
   - betaflight 4.3.0 with HGLRC HERMES 2400 RX
- user_defines: no

<img width="865" alt="RX_2 5 0" src="https://user-images.githubusercontent.com/103599102/188497152-c98579bc-a22f-4dc8-86d7-6f1d1b360823.PNG">
<img width="865" alt="RX_3 0 0_RC2" src="https://user-images.githubusercontent.com/103599102/188497155-c40b69d1-4a12-42c6-81df-b23fb76f3541.PNG">
<img width="867" alt="TX_2 5 0" src="https://user-images.githubusercontent.com/103599102/188497157-69488aeb-7bc8-4a45-8638-5a36259f038f.PNG">
<img width="863" alt="TX_3 0 0_RC2" src="https://user-images.githubusercontent.com/103599102/188497158-04e85854-fb32-4921-8729-fed987d08b34.PNG">

**Comment by pkendall64** [comment]
You have not said which flight control firmware and version you are using.

**Comment by SolkGit** [comment]
> You have not said which flight control firmware and version you are using. You also say set telemetry to off as a possible solution, and then say it does not recover if telemetry is set to off. Can you clarify which one is correct. Or is it that on EU_CE, telemetry off works and ISM2400 telemetry off does not recover?

Hello, thank you for the hint regarding flight control firmware. I'm using betaflight 4.2.0 and 4.3.0, added the information to the description. I said "CAN exit failsafe, if telemetry ratio is set to 'off' using 3.0.0-RC2"

**Comment by SunjunKim** [comment]
Do you have any DVR demonstrating the problem?

**Comment by SolkGit** [comment]
> Do you have any DVR demonstrating the problem?

I added some recordings in Details

**Comment by SolkGit** [comment]
> Seems to all be working according to spec to me. Can you provide a test case that is not working to spec? And how does telemetry have anything to do with anything, are you running VTX Admin that might be mucking up the reconnect process maybe?

I've added some recording where you can see the difference between telemetry settings in 3.0.0-RC2 (Off vs Std)

**Comment by CapnBry** [comment]
Wow, what the fuuuuuuuuudge is going on there? Everything works as I described and then it goes from FAILSAFE to FAIL SAFE. Iiiiii do not know what the heck is going on there. I'll have to check into it deeper tomorrow. Have you tried upgrading to Betaflight 4.3.1? All my testing was in 4.3.1 and it re-armed every time.

**Comment by CapnBry** [comment]
Yeah I can't reproduce your behavior at all, using the exact same settings down to the LBT, ReceiverID and VTX Admin settings. It works exactly as expected, which is that it comes back with BADRX after failsafe, I turn off the arm switch, and it is ready to go again. My quad doesn't have a GPS though so that might change the behavior slightly? Doesn't look like there is one in the video either though.

Suggestions to try (in this order):
* Update the FC to Betaflight 4.3.1
* Setting VTX Admin in the Lua to Off (this relies on telemetry being on so there's a possible interaction here, but it worked with it enabled for me)
* Disable the GPS feature in the Configuration tab of Betaflight if enabled

**Comment by SolkGit** [comment]
> Yeah I can't reproduce your behavior at all, using the exact same settings down to the LBT, ReceiverID and VTX Admin settings. It works exactly as expected, which is that it comes back with BADRX after failsafe, I turn off the arm switch, and it is ready to go again. My quad doesn't have a GPS though so that might change the behavior slightly? Doesn't look like there is one in the video either though.

I'm testing different settings now and will provide the results as fast as possible. With ELRS 2.5.0 I also could exit failsafe mode if I keep the arm switch ON during power up of radio controller, but can't if the arm switch is already OFF.

**Comment by SolkGit** [comment]
> * Update the FC to Betaflight 4.3.1
Tested with 4.3.1, same results as with 4.3.0. Noticed "BST" warning. Check the recording Update (09.09.2022 19:26).

> * Setting VTX Admin in the Lua to Off (this relies on telemetry being on so there's a possible interaction here, but it worked with it enabled for me)
How to disable VTX Admit in the Lua script. I see only "Band", "Channel", "Pwr Lvl" and "Pitmode"

> * Disable the GPS feature in the Configuration tab of Betaflight if enabled
GPS feature is disabled.

**Comment by SolkGit** [comment]
> * Update the FC to Betaflight 4.3.1

Also tested with iNav 5.1. Still no control, if radio is powered on with disarmed motors.

**Comment by CapnBry** [comment]
> How to disable VTX Admit in the Lua script. I see only "Band", "Channel", "Pwr Lvl" and "Pitmode"

You set the Band to "Off"

I just can't think of how this could actually happen. Maybe you can run the same test you've been doing, then when it is stuck no able to get out of Failsafe, plug in a USB cable to the flight controller (without unplugging the battery) and see what it says the `Arming disable flags` is when you type `status` in the CLI tab.

**Comment by SolkGit** [comment]
> I just can't think of how this could actually happen. Maybe you can run the same test you've been doing, then when it is stuck no able to get out of Failsafe, plug in a USB cable to the flight controller (without unplugging the battery) and see what it says the `Arming disable flags` is when you type `status` in the CLI tab.

Motors disarmed: Arming disable flags: FAILSAFE CLI MSP
Motors armed: Arming disable flags: FAILSAFE CLI MSP ARMSWITCH

**Comment by SolkGit** [comment]
> You set the Band to "Off"

After setting Band to "Off" I can regain control powering on the radio controller with armed and disarmed motors. Tested with ELRS 2.5.0

**Comment by SolkGit** [comment]
> > You set the Band to "Off"
> 
> After setting Band to "Off" I can regain control powering on the radio controller with armed and disarmed motors. Tested with ELRS 2.5.0

Meanwhile official rELRS release 3.0.0 is available, so I tested it. With active VTX administrator control CAN'T be regained in both cases, power on with arm switch on and off. Switching VTX administrator off regaining control works in every situation.

**Comment by dentex** [comment]
> Meanwhile official ELRS release 3.0.0 is available, so I tested it. With active VTX administrator control CAN'T be regained in both cases, power on with arm switch on and off. Switching VTX administrator off regaining control works in every situation.
Sorry about not adding much to the discussion, I was just scrolling through issues before upgrading to ELRS 3.0.0, because I have a working setup (with GPS) on 2.5.0... 
So can you confirm, just leave the VTX administrator off and we're good to go?

**Comment by CapnBry** [comment]
> Meanwhile official ELRS release 3.0.0 is available, so I tested it. With active VTX administrator control CAN'T be regained in both cases, power on with arm switch on and off. Switching VTX administrator off regaining control works in every situation.

Thanks for doing all the testing and reporting back. Ok so we now know _where_ the problem lies but I'm not sure why it is happening still, or what the difference is between 3.x and 2.x that brings it up (both send VTX Admin info in the same way).

I'll have to dig into this some more and see if I can reproduce it somehow, as it still works for me even with VTX Admin on.

**Comment by EhAye** [comment]
Disabling VTX Administrator as mentioned in this thread also seems to have fixed most of my problems.

For me, while inav is disarmed, if my yaw stick (channel 4) crosses over 1500 then it causes hickups in channel response, and eventually a failsafe within a couple seconds. The failsafe won't clear until i reboot the wing. 

- If i set EdgeTX's Yaw/Channel 4 "PPM Center" to 1600, THEN power up my wing, i'm able to move yaw around on the right side, but if i move it to the left it failsafes.
- If i set EdgeTX's Yaw/Channel 4 "PPM Center" to 1400, THEN power up my wing, i'm able to move yaw around on the left side, but if i move it to the right it failsafes.
(Moving my stick past 1500, to the opposite 'side' will trigger the failsafe)

The initial symptoms were random failsafes, and i could trigger the failsafes with some stick commands. I think the random failsafes were caused by Yaw stick jitter pushing it past the 1500 mark, triggering a failsafe. And SOME of my "stick commands failsafes" were simply me moving the stick far to the corner, past 1500.

I think other people reporting random failsafes are probably also having the yaw jitter push it past 1500.

This only happens while disarmed. Once i've armed, the "yaw 1500 failsafe" doesn't happen and everything seems to function normally.
Disabling inav's telemetry also seems to fix the "yaw 1500 failsafe".
**But if i disable VTX Administrator, i can leave inav telemetry enabled.**


I'm still having other failsafe issues but i think those are due to a different problem with the h743-wing and inav memory writes, as they are only triggered by very specific stick commands.

I'm using a Matek h743-Wing V2, inav 5.1, ELRS 3.0.1, HM EP1.
Also tried on Matek D24D, inav 4.1, ELRS 2.5.1. Same issues.

**Comment by CapnBry** [comment]
That is certainly a lot of good information and troubleshooting to narrow it down!

I run VTX Admin though and also have a Yaw stick that I use with no issues, so it doesn't seem intrinsic to ExpressLRS itself. VTX Admin does send commands on every RX connection though:
* Set VTX channel / band and optionally power / pit mode
* "Save EEPROM" (MSP command)

Is it possible that the yaw channel causes a disconnect or failsafe in iNav and then it can not clear that until after it can do an EEPROM save or something? It seems to me that there's something else in play here that's keying off your stick position, especially since everybody uses the yaw channel. I do not believe _other people reporting random failsafes are probably also having the yaw jitter push it past 1500._, I think this is very specific to your configuration.

Have you tried saving a backup of the iNav config, doing a fresh install with chip erase, just enable the Serial RX, then creating a new model on the handset that just sends CH1-CH5 with iNav telemetry, see if it fails? Then add the VTX setup to iNav, test it again. See if VTX Admin works properly. Then keep adding your saved config backup until it starts failing when you move the yaw stick.

**Comment by pkendall64** [comment]
Quite possible related to, or caused by #1773
