### ISSUE TITLE
STM32 can't boot into DFU

### ISSUE THREAD

**Issue by ASDosjani** [ExpressLRS/ExpressLRS#2051]
Some of the users reported in Betaflight discord that they can't flash their FCs because the receiver blocking it. I experienced this as well and I had to desolder the receiver to flash my FC.

My idea is that the Betaflight FC sends a mute command to the receiver before it tries to go into DFU. The receiver doesn't send any data to the FC for like 10s and I think it would solve the problem.

**Comment by CapnBry** [comment]
Workaround: Wait for the RX to go to wifi mode and it won't put out any CRSF any more.

**Comment by ASDosjani** [comment]
> Workaround: Wait for the RX to go to wifi mode and it won't put out any CRSF any more.

Thanks for the tip, but it's not a proper solution in my opinion.

**Comment by pkendall64** [comment]
The RX should not be outputting anything to the FC if there is not a connection to a transmitter!

**Comment by ASDosjani** [comment]
> The RX should not be outputting anything to the FC if there is not a connection to a transmitter!

It's possible, I don't know the elrs firmware but then it's maybe pulling down the data line to the ground or vcc thus blocking the communication.

**Comment by CapnBry** [comment]
> The RX should not be outputting anything to the FC if there is not a connection to a transmitter!

It puts out a LinkStats packet every time it cycles rates, which is a lot of data right up front as it goes through F1000, F500, D500, D250 in the first second or so. There's also the ESP bootloader which puts out information before we even start our code, which can not be disabled. As long as the RX is waiting for a connection it will be spitting out LinkStats to the FC. Once it goes to wifi all that stops.

I don't think waiting 60 seconds after plugging is too much of an inconvenience as a workaround. A user still needs to navigate through the Betaflight Firmware Flasher screen, selecting their firmware, and possibly building it using the new cloud building system, which can easily take the entire 60 seconds. A user can also connect to the RX and force it to wifi from the ExpressLRS Lua, or by holding the button on the RX for 5 seconds too, if 60 seconds is too much of an ask.

Another workaround is to use a different UART for the RX, one that doesn't interfere with the DFU flashing process. Any GPS will similarly disrupt the DFU flash, so the issue is not unique to ExpressLRS.

**Comment by ASDosjani** [comment]
Thanks for the detailed answer, I know it's not a unique problem, I'm just proposing a solution for elrs receivers since it's open source and the firmware can be modified. Frsky and other receivers won't benefit from this since they are closed source but most of the users using elrs imho and gps usually doesn't soldered to UART 1, it has a different UART on the back of the FCs for the shortest and cleanest cables.

**Comment by nightflasher** [comment]
experienced the same behavior on DarwinFPV (MatekF411/DarwinF411) AIO - but only happens, when TX is transmitting/connected to the rx. turning off the tx helps, but sometimes "i wonder what is wrong?" - affects emuFlight and QuickSilver as well.

**Comment by kamnxt** [comment]
So in case anyone finds this and wonders how to flash a board that outputs 5V even when only USB is connected without desoldering the RX every time, I suppose the workaround is to wait until the RX goes into WiFi mode and only then update the firmware on the flight controller?
