### ISSUE TITLE
Forward all CRSF-Command packets from handset to receiver-serial-out belonging to a set of special extended destinations

### ISSUE THREAD

**Issue by wimalopaan** [ExpressLRS/ExpressLRS#2474]
## Current Behavior

CRSF-Packets with extended-destination `0xc8` are forwarded from handset to receiver-out. Other extended destinations are not forwarded. 

There could be other devices connected to the receiver. CRSF / ELRS is not limited to work together with flight-controllers. there might be other: e.g. simple listening devices on the receiver-serial-out like CRSF/SBus/Pwm-converter or similar. In these cases it should be possible to use the radio-link as a transparent link that forwards packages, at least those with a special extended destination (may a collection of predefined)  beside from `0xc8`.

## Possible Solution (Not obligatory)

Define a set of forwarded extended destinations aside from `0xc8`.

**Comment by schugabe** [comment]
The "problem" here is that the list of possible receivers is very limited/tied to TBS products. Without an open specification it's not possible to extend the protocol.

The "easy" way would be to use 0xc8 for the other devices since you would not use a FC and a PWM converter at the same time. Even if you have a listening device connected to the UART on the rx you get the frames sent to 0xc8 (and everything else).

Broadcast frames (like rc data+tlm) is forwarded independent of the address. 

I'm not sure what we should/could change here.
