### ISSUE TITLE
UART on EP1/EP2 (esp8285) RX-as-TX is not inverted

### ISSUE THREAD

**Issue by wimalopaan** [ExpressLRS/ExpressLRS#2500]
The title says it all: using an esp8285 based RX as a TX module, the firmware does not invert the serial polarity.

Verfified on EP1/2 and ELRX 3.3.1,

**Comment by CapnBry** [comment]
esp8285 doesn't support half duplexing its UART so that's why they RX-as-TX is called a "DupleTX", as in it only can work in full duplex as an internal module. I tried getting it working half duplex and was never able to find any bits to flip to make it work without additional hardware (and if that's the case it all can be dealt with in that manner).

If you want an **external** RX as TX, you'll have to use an ESP32-based RX. ESP8285 is just for internal / connecting to a PC / project microcontroller. Using an EP1 as an external TX is not very useful and I don't think we want to have a bunch of special code to support it, if it even is possible.
