### ISSUE TITLE
Occasionally wrong RSSI values if no connection is present

### ISSUE THREAD

**Issue by catkira** [ExpressLRS/ExpressLRS#2730]
## Current Behavior

I have my Radiomaster RP1 2.4 GHz module connected to betaflight 4.5. When no ELRS connection is present, I sometimes see the RSSI value jump from 0 to 1022.

## Your Environment

- TX hardware: not relevant
- RX hardware: Radiomaster RP1 2.4 GHz
- Handset model: not relevant
- OpenTX version (including nightly number) : not relevant
- ExpressLRS version (TX & RX MUST MATCH): 3.4.1
- Packet Rate: not relevant
- Telemetry Ratio: not relevant
- user_defines: none

I have also filed a bug report at betaflight about this : https://github.com/betaflight/betaflight/issues/13652
but I think it is likely a ELRS problem.

**Comment by pkendall64** [comment]
This only happens before the transmitter connects to the receiver (or after a failsafe and "lock on first connection" is disabled in the receiver).
The reason is that when the receiver switches packet rate, hunting for a connection, it sends a LinkStatistics packet to the FC so the OSD can display the new packet rate. In the LinkStatistics packet there is the RSSI, but because we have not had a connection, the value is uninitialised i.e. 0.

Why Betaflight Configurator is displaying 100, is probably because it is scaling the dBm to the percentage based RSSI?
