### ISSUE TITLE
Warning with usupported crustal

### ISSUE THREAD

**Issue by Norinke** [ExpressLRS/ExpressLRS#2922]
## Current Behavior

Warning with wrong crystal, but it is BETAFPV SuperD 900 RX 
and when i connect to TX, Link not stable, always jump around 90-100

Chip is ESP32-PICO-D4 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
WARNING: Detected crystal freq 79.80MHz is quite different to normalized freq 40MHz. Unsupported crystal in use?
Crystal is 40MHz
MAC: 14:2b:2f:a7:2c:b8
Stub is already running. No upload is necessary.
WARNING: Failed to communicate with the flash chip, read/write operations will fail. Try checking the chip connections or removing any other hardware connected to IOs.
Configuring flash size...
Warning: Could not auto-detect Flash size (FlashID=0x0, SizeID=0x0), defaulting to 4MB
Flash will be erased from 0x00010000 to 0x0010dfff...
Compressed 1039084 bytes to 684038...

**Comment by pkendall64** [comment]
This is a spurious message from the ESP flashing tool.

If you have an issue with the LQ jumping around, you need to provide much more information. What transmitter, are both the TX and RX using LBT EU firmware or something else.
It would be much quicker to provide help in the #help-and-support channel on discord rather than playing issue tracker tag.
