### ISSUE TITLE
[MAVLINK] Yaapu telemetry script does not work with Mavlink via ELRS

### ISSUE THREAD

**Issue by menschel** [ExpressLRS/ExpressLRS#3074]
When selecting Link Mode = Mavlink, the telemetry is no longer forwarded to the handset and this breaks the [Yaapu](https://github.com/yaapu/FrskyTelemetryScript) telemetry script in the handset.

## Steps to Reproduce

Follow the guide for [Mavlink](https://www.expresslrs.org/software/mavlink/) and observe that Yaapu Telemetry Script in the handset does not get any data.

## Possible Solution (Not obligatory)

After some research, I'm positive that `convert_mavlink_to_crsf_telem` in [MAVLink.cpp](https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/MAVLink/MAVLink.cpp) would need to create the PassThrough messages to make Yaapu Script work again.

I'll investigate and eventually push PR later.

## Details
Yaapu reads some kind of CRSF Passthrough packets that seem to derived from some Frsky S-Port format.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp

Reference Issue https://github.com/yaapu/FrskyTelemetryScript/issues/259

## Your Environment

ELRS V3.5.3
Independent of Hardware.

**Comment by menschel** [comment]
I'll build from trunk just to verify I'm not pointing at something that is already fixed.

**Comment by menschel** [comment]
I realize this is is now a feature request and not a bug.

**Comment by menschel** [comment]
Solved by https://github.com/ExpressLRS/ExpressLRS/pull/3077

**Comment by Roasted715Jr** [comment]
Hi, was this actually fixed? I saw that the PR was merged in April, and my hardware is currently on 3.5.6. Yaapu still complains that it's not getting any telemetry, though it is getting GPS coordinates. The EdgeTX telemetry screen shows I'm currently getting 24 telemetry items, whereas when running on CRSF I get 36. Some of the items I'm not receiving through MAVLink include ARM, Thr, GAlt, and GSpd.

I can provide more information if need be.

**Comment by pkendall64** [comment]
> Hi, was this actually fixed? I saw that the PR was merged in April, and my hardware is currently on 3.5.6. Yaapu still complains that it's not getting any telemetry, though it is getting GPS coordinates. 

It is not in the 3.x line, it is merged into the master branch which will become the 4.x line _when_ it is released.

**Comment by Roasted715Jr** [comment]
Thanks for the help, flashed the master branch and it's working now :)

**Comment by SvenIffert** [comment]
> Thanks for the help, flashed the master branch and it's working now :)

Could you please be more specific? What exactly did you flash? Thank you!

**Comment by Roasted715Jr** [comment]
> > Thanks for the help, flashed the master branch and it's working now :)
> 
> Could you please be more specific? What exactly did you flash? Thank you!

Sorry, don't check my github notifications.

At the time, I just flashed what was on the master branch at that point. I selected the specific branch through the ELRS configurator.

**Comment by ghost** [comment]
Sorry, I did not follow this discussion, since I broke up with ArduPilot 
project after the AVY / Frontex forum incident.

Technically, this feature could have been cherry-picked to 
3.x.x-maintenance after it was merged to master and would have been 
available since 3.5.5 that way.

There never was a technical reason to delay this until 4.0.

Cheers

**Comment by Gourav1997** [comment]
Hey, I am using Radiomaster ZORRO. It is giving the “NO TELEMETRY“ error. All the sensors are detected in the Telemetry tab of EdgeTX but it is showing NO TELEMETRY when I run YAAPU telemetry script via the telem button on the radio. In the YAAPU config script CRSF support and Px4 mode is switched on.

BTW I would like to clarify I am using the mavlink via elrs where the serial protocol is set to 2 (MAVLINK 2) instead of 23 (RC IN) as now ELRS can directly support 16 channels and telemetry.

The setup I am currently using is TBS lucid h7 running on arducopter 4.6.3 with Radiomaster ZORRO running ELRS version of 3.6.0 and ELRS BACKPACK version 1.5.3 for telemetry. The reciever is Radiomaster RP1 V2 with latest ELRS version of 3.6.0. Also tried with pixhawk cube orange plus running 4.4.4, 4.5.7 and 4.6.3. Got the same results. It is connecting via the ELRS BACKPACK to mission planner with full telemetry when I am using both the flight controllers.


From the above conversation it seems like you solved this issue. If yes, please guide me how to do it.
