### ISSUE TITLE
Support for Radio master TX16 Multiprotocol Module possible?

### ISSUE THREAD

**Issue by evildronepilot** [ExpressLRS/ExpressLRS#586]
Is it possible to get support for the internal multi-protocol module built into TX16.. radio?
Having the option to select the 2.4 ELRS and bind with, for example, ghost RX... would be a mind-blowing feature.
In deferent words, Is it possible to make Express LRS protocol available for the Internal Multi-Protocol TX module?

**Comment by evildronepilot** [comment]
Openned with OpenTX 

https://github.com/opentx/opentx/issues/8495

**Comment by raphaelcoeffic** [comment]
@evildronepilot do you mean having ELRS as an internal module? Or do you mean integrating ELRS into MPM?

**Comment by sweebee** [comment]
No not possible, the multi-protocol module doesn't have the lora chipset.

**Comment by evildronepilot** [comment]
> No not possible, the multi-protocol module doesn't have the lora chipset.

Thanks for looking into this. All thumbs up!

**Comment by tipouic** [comment]
> 
> 
> No not possible, the multi-protocol module doesn't have the lora chipset.

Hi the multi-protocol have a free SPI port on the PCB to add another chipset.
Alessandro had started to port his code on it for 868-916Mhz but he stopped because the code changed too much. He had put an RFM95 from memory but now the Jumper T18 radio comes out with a 5in1 pcb (sx1276). 
[https://github.com/AlessandroAU/DIY-Multiprotocol-TX-Module/tree/adds-ExpressLRS-support](https://github.com/AlessandroAU/DIY-Multiprotocol-TX-Module/tree/adds-ExpressLRS-support)
