### ISSUE TITLE
Touch Screen LUA script support

### ISSUE THREAD

**Issue by rentacheese** [ExpressLRS/ExpressLRS#973]
I would like a way to interact with ExpressLRS's LUA script using the touch screen, I'm running EdgeTX on my nirvana radio and currently, there is no way to interact with the LUA script. all I can do is run the LUA script and close it.
It would be nice to have touch support so I could change the output power and packet rate.

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by Neukom720** [comment]
@rentacheese edgetx 2.6 rc1 Santa "NV14 support using trim hats as keys in standalone Lua scripts" I'm going to try it tonight because I had to flash back to latest flysky opentx because of no touchscreen but hopefully until touchscreen lua is added, at least we have this! Edgetx and ExpressLRS devs are awesome and do such quick and great work, can't thank all you guys enough for all you contributions to our community! Open source for the win!!!!

**Comment by mece** [comment]
Can confirm it works very nicely (using nightly from 12.1) but I can't seem to get out of the lua script. RTN (which apparently is left trim hat push) reloads the data from the module.

**Comment by Neukom720** [comment]
Also something that is super helpful if your ever having issues with any of the newer or older elrs lua is that the crossfire lua works and has all the functionality. So if any problems in the future you can try that until it is resolved. The new 2.0 elrs lua is really nice and is working for me perfect on edgetx 2.6 Santa on my nv14 and I will not be going back to opentx, also on elrs 2.01 and it's awesome!
